parser: 'babel-eslint'

extends:
    - 'eslint:recommended'

env:
    commonjs: true
    es6: true
    node: true
    browser: false

parserOptions:
    ecmaFeatures:
        experimentalObjectRestSpread: true
        jsx: false
    sourceType: 'module'

globals:
    'strapi': true

rules:
    no-console: 1 # warn
    no-unused-vars: 1 # warn
    indent:
        - 'error'
        - 4
        # - switchCase: 1
    linebreak-style:
        - 'error'
        - 'unix'
    quotes:
        - 'error'
        - 'single'
    semi:
        - 'error'
        - 'always'
